FROM sclinux1:443/repo_rdma/cityscaps:fizzbb

#RUN mkdir /rdma && cd /rdma && wget https://content.mellanox.com/ofed/MLNX_OFED-5.7-1.0.2.0/MLNX_OFED_LINUX-5.7-1.0.2.0-ubuntu18.04-x86_64.tgz && tar xzf MLNX_OFED_LINUX-5.7-1.0.2.0-ubuntu18.04-x86_64.tgz && cd MLNX_OFED_LINUX-5.7-1.0.2.0-ubuntu18.04-x86_64 && ./mlnxofedinstall
# RUN git clone https://github.com/microsoft/Freeflow.git
